project_id = "elmaneko-3d-local"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/accept-invite"]
enable_signup = true
enable_confirmations = false
