import { useEmpresa, useUpdateEmpresa } from './data/useCompanyData';
import { 
  useFilamentos, useAddFilamento, useUpdateFilamento, useDeleteFilamento,
  useInsumos, useAddInsumo, useUpdateInsumo, useDeleteInsumo,
  useCompras, useAddCompra 
} from './data/useFilamentsData';
import { 
  useImpressoras, useAddImpressora, useUpdateImpressora, useDeleteImpressora,
  useTarifasEnergia, useAddTarifaEnergia 
} from './data/usePrintersData';
import { 
  useProdutos, useAddProduto, useUpdateProduto, useDeleteProduto,
  useProducoes, useAddProducao, useUpdateProducaoStatus, useUpdateProducao
} from './data/useProductsData';
import { 
  useClientes, useAddCliente, useUpdateCliente, useDeleteCliente,
  useOrcamentos, useAddOrcamento, useUpdateOrcamento, useDeleteOrcamento,
  useVendas, useAddVenda, useUpdateVenda, useDeleteVenda, useConverterOrcamentoEmVenda
} from './data/useSalesData';
import { 
  useContasFinanceiras, useAddContaFinanceira, useUpdateContaFinanceira, useDeleteContaFinanceira,
  useCategoriasFinanceiras, useAddCategoriaFinanceira, useUpdateCategoriaFinanceira, useDeleteCategoriaFinanceira,
  useCentrosCusto, useAddCentroCusto, useUpdateCentroCusto, useDeleteCentroCusto,
  useLancamentosFinanceiros, useAddLancamentoFinanceiro, useLiquidarLancamento, useConciliateLancamento, useCancelLancamento, useDeleteLancamento,
  useMovimentacoesFinanceiras, useTransferenciasFinanceiras, useAddTransferenciaFinanceira,
  useAuditoriaFinanceira, useAddAuditLog, useSyncFinancialEntries
} from './data/useFinancialData';

export function useData() {
  return {
    // Company
    useEmpresa,
    useUpdateEmpresa,
    // Filaments & Supplies & Purchases
    useFilamentos,
    useAddFilamento,
    useUpdateFilamento,
    useDeleteFilamento,
    useInsumos,
    useAddInsumo,
    useUpdateInsumo,
    useDeleteInsumo,
    useCompras,
    useAddCompra,
    // Printers & Tariffs
    useImpressoras,
    useAddImpressora,
    useUpdateImpressora,
    useDeleteImpressora,
    useTarifasEnergia,
    useAddTarifaEnergia,
    // Deprecated aliases retained temporarily for existing screens.
    useTarifas: useTarifasEnergia,
    useAddTarifa: useAddTarifaEnergia,
    // Products & Production
    useProdutos,
    useAddProduto,
    useUpdateProduto,
    useDeleteProduto,
    useProducoes,
    useAddProducao,
    useUpdateProducaoStatus,
    useUpdateProducao,
    // Clients & Sales & Budgets
    useClientes,
    useAddCliente,
    useUpdateCliente,
    useDeleteCliente,
    useOrcamentos,
    useAddOrcamento,
    useUpdateOrcamento,
    useDeleteOrcamento,
    useVendas,
    useAddVenda,
    useUpdateVenda,
    useDeleteVenda,
    useConverterOrcamentoEmVenda,
    // Financial
    useContasFinanceiras,
    useAddContaFinanceira,
    useUpdateContaFinanceira,
    useDeleteContaFinanceira,
    useCategoriasFinanceiras,
    useAddCategoriaFinanceira,
    useUpdateCategoriaFinanceira,
    useDeleteCategoriaFinanceira,
    useCentrosCusto,
    useAddCentroCusto,
    useUpdateCentroCusto,
    useDeleteCentroCusto,
    useLancamentosFinanceiros,
    useAddLancamentoFinanceiro,
    useLiquidarLancamento,
    useConciliateLancamento,
    useCancelLancamento,
    useDeleteLancamento,
    useMovimentacoesFinanceiras,
    useTransferenciasFinanceiras,
    useAddTransferenciaFinanceira,
    useAuditoriaFinanceira,
    useAddAuditLog,
    useSyncFinancialEntries
  };
}

export {
  useEmpresa,
  useUpdateEmpresa,
  useFilamentos,
  useAddFilamento,
  useUpdateFilamento,
  useDeleteFilamento,
  useInsumos,
  useAddInsumo,
  useUpdateInsumo,
  useDeleteInsumo,
  useCompras,
  useAddCompra,
  useImpressoras,
  useAddImpressora,
  useUpdateImpressora,
  useDeleteImpressora,
  useTarifasEnergia,
  useAddTarifaEnergia,
  useTarifasEnergia as useTarifas,
  useAddTarifaEnergia as useAddTarifa,
  useProdutos,
  useAddProduto,
  useUpdateProduto,
  useDeleteProduto,
  useProducoes,
  useAddProducao,
  useUpdateProducaoStatus,
  useUpdateProducao,
  useClientes,
  useAddCliente,
  useUpdateCliente,
  useDeleteCliente,
  useOrcamentos,
  useAddOrcamento,
  useUpdateOrcamento,
  useDeleteOrcamento,
  useVendas,
  useAddVenda,
  useUpdateVenda,
  useDeleteVenda,
  useContasFinanceiras,
  useAddContaFinanceira,
  useUpdateContaFinanceira,
  useDeleteContaFinanceira,
  useCategoriasFinanceiras,
  useAddCategoriaFinanceira,
  useUpdateCategoriaFinanceira,
  useDeleteCategoriaFinanceira,
  useCentrosCusto,
  useAddCentroCusto,
  useUpdateCentroCusto,
  useDeleteCentroCusto,
  useLancamentosFinanceiros,
  useAddLancamentoFinanceiro,
  useLiquidarLancamento,
  useConciliateLancamento,
  useCancelLancamento,
  useDeleteLancamento,
  useMovimentacoesFinanceiras,
  useTransferenciasFinanceiras,
  useAddTransferenciaFinanceira,
  useAuditoriaFinanceira,
  useAddAuditLog,
  useSyncFinancialEntries
};
